# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.SlugField(unique=True, verbose_name='URL: /ping/'),
        ),
    ]
