# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20161014_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lastPingIP',
            field=models.GenericIPAddressField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Leave this as "No" until you start pinging this system', verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='alertedContacts',
            field=models.ManyToManyField(help_text='Note: you will automatically recieve an email, no need to add your email here.    ', to='status.Contact', verbose_name='Emails to send alerts to'),
        ),
    ]
