# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_auto_20161014_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='alertedContacts',
            field=models.ManyToManyField(blank=True, help_text='Note: you will automatically recieve an email, no need to add your email here.    ', to='status.Contact', verbose_name='Emails to send alerts to'),
        ),
    ]
