# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_auto_20161014_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_start', models.DateTimeField(auto_now_add=True, verbose_name='Downtime Started On')),
                ('down_end', models.DateTimeField(editable=False, null=True, verbose_name='Downtime Ended On')),
                ('ongoing', models.BooleanField(default=True)),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='status.Project')),
            ],
        ),
    ]
